baseURL: https://bfloeser.netlify.com
languageCode: en-us
theme: "toha"

# Manage languages
defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
  de:
    languageName: Deutsch
    weight: 1

# Control of TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

params:
  background: "images/site/scotland_large_dark.jpg"
  # fonts: true

  logo:
    main: "images/site/logo.png"
    inverted: "images/site/logolite.png"
    favicon: "images/site/logolite.png"

  features:
    blog:
      enable: False
      # shareButtons:
      # email: True

  # enableTOC: true
  enableTags: false

  newsletter:
    enable: false
  
  footer:
    enable: true
    template: footer.html
    navigation:
      enable: false
    
    contactMe:
      enable: false
    
    credentials:
      enable: true
    
    disclaimer:
      enable: true


 
