[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.87.0"

[context.production.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"